In [1]:
import numpy as np
from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise
import matplotlib.pyplot as plt

In [2]:
f = KalmanFilter (dim_x=2, dim_z=1)

In [3]:
f.x = np.array([[2.],    # position
                [0.]])   # velocity

In [4]:
f.F = np.array([[1.,0.2],  # 1 time 
                [0.,1.]])  # 0 1 

In [5]:
f.H = np.array([[1.,0.]])

In [6]:
f.P = np.array([[10,    0.],
                [   0., 10] ])

In [7]:
f.R = np.array([[5.]])

In [8]:
f.Q = Q_discrete_white_noise(dim=2, dt=0.1, var=0.13)

In [9]:
f.Q

array([[3.25e-06, 6.50e-05],
       [6.50e-05, 1.30e-03]])

In [10]:
f.predict()

In [11]:
f.x

array([[2.],
       [0.]])

In [12]:
sensor_reading = np.array([3.])

In [13]:
f.update(sensor_reading)

In [14]:
f.x

array([[2.80620157],
       [0.15504126]])

In [15]:
acceleration_array = np.arange(30)

In [16]:
kalman_buffer = np.array([f.x[0][0],f.x[1][0]])

In [17]:
kalman_buffer

array([2.80620157, 0.15504126])

In [18]:
kalman_output = np.array([f.x[0][0],f.x[1][0]])

In [19]:
kalman_output = np.concatenate(([kalman_output], [kalman_buffer]),axis=0)

In [20]:
kalman_output

array([[2.80620157, 0.15504126],
       [2.80620157, 0.15504126]])

In [21]:
for acceleration_reading in acceleration_array:
    kalman_buffer = np.array([f.x[0][0],f.x[1][0]])
    kalman_output = np.concatenate((kalman_output, [kalman_buffer]),axis=0)
    f.update(acceleration_reading)    

In [22]:
kalman_output

array([[ 2.80620157,  0.15504126],
       [ 2.80620157,  0.15504126],
       [ 2.80620157,  0.15504126],
       [ 1.55364806, -0.08583829],
       [ 1.38278931, -0.11869627],
       [ 1.52834467, -0.09070441],
       [ 1.80917431, -0.03669784],
       [ 2.16024653,  0.03081714],
       [ 2.55245684,  0.10624341],
       [ 2.97082848,  0.18670079],
       [ 3.40686785,  0.27055586],
       [ 3.85539907,  0.35681326],
       [ 4.31308812,  0.4448318 ],
       [ 4.7776905 ,  0.53417985],
       [ 5.24763981,  0.62455617],
       [ 5.7218096 ,  0.71574413],
       [ 6.1993691 ,  0.80758398],
       [ 6.67969214,  0.89995528],
       [ 7.16229784,  0.99276556],
       [ 7.64681077,  1.08594262],
       [ 8.13293355,  1.17942928],
       [ 8.62042757,  1.27317964],
       [ 9.10909915,  1.36715645],
       [ 9.59878946,  1.46132918],
       [10.089367  ,  1.55567254],
       [10.58072195,  1.65016539],
       [11.07276192,  1.74478999],
       [11.56540859,  1.83953126],
       [12.05859514,